import AppThemeProvider from "@/theme/theme-provider";
import "./globals.css";
import NotificationsProvider from "@/hooks/useNotifications/NotificationsProvider";
import DialogsProvider from "@/hooks/useDialogs/DialogsProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body>
        <AppThemeProvider>
          <NotificationsProvider>
            <DialogsProvider>{children}</DialogsProvider>
          </NotificationsProvider>
        </AppThemeProvider>
      </body>
    </html>
  );
}
